USE [Kørselslog]

GO

create table post_nr_by (
	post_nr int,
	by_navn varchar(20),

	primary key (post_nr)
);

INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('0800','Høje Taastrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2000','Frederiksberg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2150','Nordhavn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2412','Grønland')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2500','Valby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2600','Glostrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2605','Brøndby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2610','Rødovre')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2620','Albertslund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2625','Vallensbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2630','Taastrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2635','Ishøj')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2640','Hedehusene')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2650','Hvidovre')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2660','Brøndby Strand')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2665','Vallensbæk Strand')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2670','Greve')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2680','Solrød Strand')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2690','Karlslunde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2700','Brønshøj')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2720','Vanløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2730','Herlev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2740','Skovlunde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2750','Ballerup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2760','Måløv')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2765','Smørum')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2770','Kastrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2791','Dragør')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2800','Kongens Lyngby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2820','Gentofte')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2830','Virum')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2840','Holte')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2850','Nærum')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2860','Søborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2870','Dyssegård')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2880','Bagsværd')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2900','Hellerup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2920','Charlottenlund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2930','Klampenborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2942','Skodsborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2950','Vedbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2960','Rungsted Kyst')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2970','Hørsholm')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2980','Kokkedal')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('2990','Nivå')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3000','Helsingør')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3050','Humlebæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3060','Espergærde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3070','Snekkersten')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3080','Tikøb')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3100','Hornbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3120','Dronningmølle')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3140','Ålsgårde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3150','Hellebæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3200','Helsinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3210','Vejby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3220','Tisvildeleje')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3230','Græsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3250','Gilleleje')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3300','Frederiksværk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3310','Ølsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3320','Skævinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3330','Gørløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3360','Liseleje')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3370','Melby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3390','Hundested')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3400','Hillerød')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3450','Allerød')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3460','Birkerød')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3480','Fredensborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3490','Kvistgård')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3500','Værløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3520','Farum')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3540','Lynge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3550','Slangerup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3600','Frederikssund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3630','Jægerspris')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3650','Ølstykke')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3660','Stenløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3670','Veksø Sjælland')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3700','Rønne')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3720','Aakirkeby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3730','Nexø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3740','Svaneke')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3751','Østermarie')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3760','Gudhjem')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3770','Allinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3782','Klemensker')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('3790','Hasle')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4000','Roskilde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4030','Tune')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4040','Jyllinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4050','Skibby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4060','Kirke Såby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4070','Kirke Hyllinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4129','Ringsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4130','Viby Sjælland')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4140','Borup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4160','Herlufmagle')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4171','Glumsø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4173','Fjenneslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4180','Sorø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4200','Slagelse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4220','Korsør')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4230','Skælskør')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4241','Vemmelev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4242','Boeslunde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4270','Høng')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4281','Gørlev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4296','Nyrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4300','Holbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4330','Hvalsø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4340','Tølløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4350','Ugerløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4390','Vipperød')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4400','Kalundborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4420','Regstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4440','Mørkøv')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4450','Jyderup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4460','Snertinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4470','Svebølle')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4480','Store Fuglede')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4490','Jerslev Sjælland')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4532','Gislinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4534','Hørve')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4540','Fårevejle')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4550','Asnæs')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4560','Vig')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4571','Grevinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4572','Nørre Asmindrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4573','Højby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4581','Rørvig')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4583','Sjællands Odde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4591','Føllenslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4592','Sejerø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4593','Eskebjerg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4600','Køge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4621','Gadstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4622','Havdrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4623','Lille Skensved')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4632','Bjæverskov')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4640','Faxe')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4652','Hårlev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4653','Karise')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4681','Herfølge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4682','Tureby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4684','Holmegaard')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4690','Haslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4700','Næstved')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4733','Tappernøje')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4736','Karrebæksminde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4750','Lundby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4760','Vordingborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4771','Kalvehave')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4772','Langebæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4773','Stensved')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4791','Borre')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4792','Askeby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4793','Bogø By')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4800','Nykøbing Falster')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4840','Nørre Alslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4850','Stubbekøbing')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4862','Guldborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4863','Eskilstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4871','Horbelev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4872','Idestrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4873','Væggerløse')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4874','Gedser')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4880','Nysted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4892','Kettinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4900','Nakskov')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4912','Harpelunde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4913','Horslunde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4920','Søllested')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4930','Maribo')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4941','Bandholm')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4944','Fejø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4945','Femø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4951','Nørreballe')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4952','Stokkemarke')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4953','Vesterborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4960','Holeby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4970','Rødby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('4990','Sakskøbing')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5290','Marslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5300','Kerteminde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5320','Agedrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5330','Munkebo')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5350','Rynkeby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5370','Mesinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5380','Dalby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5390','Martofte')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5400','Bogense')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5450','Otterup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5462','Morud')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5463','Harndrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5464','Brenderup Fyn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5466','Asperup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5471','Søndersø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5474','Veflinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5485','Skamby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5491','Blommenslyst')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5492','Vissenbjerg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5500','Middelfart')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5540','Ullerslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5550','Langeskov')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5560','Aarup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5580','Nørre Aaby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5591','Gelsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5592','Ejby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5600','Faaborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5601','Lyø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5603','Bjørnø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5610','Assens')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5631','Ebberup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5642','Millinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5672','Broby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5683','Haarby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5690','Tommerup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5700','Svendborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5771','Stenstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5772','Kværndrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5792','Årslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5800','Nyborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5853','Ørbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5854','Gislev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5856','Ryslinge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5863','Ferritslev Fyn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5871','Frørup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5874','Hesselager')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5881','Skårup Fyn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5882','Vejstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5883','Oure')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5892','Gudbjerg Sydfyn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5900','Rudkøbing')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5932','Humble')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5935','Bagenkop')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5943','Strynø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5953','Tranekær')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5960','Marstal')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5965','Birkholm')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5970','Ærøskøbing')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('5985','Søby Ærø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6000','Kolding')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6040','Egtved')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6051','Almind')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6052','Viuf')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6064','Jordrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6070','Christiansfeld')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6091','Bjert')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6092','Sønder Stenderup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6093','Sjølund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6094','Hejls')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6100','Haderslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6200','Aabenraa')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6210','Barsø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6230','Rødekro')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6240','Løgumkloster')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6261','Bredebro')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6270','Tønder')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6280','Højer')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6300','Gråsten')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6310','Broager')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6340','Kruså')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6392','Bolderslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6400','Sønderborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6430','Nordborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6600','Vejen')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6660','Lintrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6670','Holsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6700','Esbjerg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6753','Agerbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6760','Ribe')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6800','Varde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6857','Blåvand')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6862','Tistrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6950','Ringkøbing')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('6960','Hvide Sande')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7000','Fredericia')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7029','Fredericia')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7080','Børkop')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7100','Vejle')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7160','Tørring')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7171','Uldum')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7173','Vonge')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7182','Bredsten')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7184','Vandel')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7190','Billund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7200','Grindsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7250','Hejnsvig')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7362','Hampen')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7400','Herning')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7429','Herning')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7430','Ikast')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7441','Bording')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7442','Engesvang')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7451','Sunds')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7500','Holstebro')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7550','Sørvad')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7560','Hjerm')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7570','Vemb')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7600','Struer')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7620','Lemvig')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7673','Harboøre')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7680','Thyborøn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7700','Thisted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7730','Hanstholm')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7790','Thyholm')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7800','Skive')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7830','Vinderup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7840','Højslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7870','Roslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('7950','Erslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8229','Risskov Ø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8230','Åbyhøj')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8240','Risskov')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8245','Risskov Ø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8250','Egå')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8260','Viby J')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8270','Højbjerg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8300','Odder')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8305','Samsø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8320','Mårslet')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8330','Beder')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8340','Malling')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8350','Hundslund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8355','Solbjerg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8361','Hasselager')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8362','Hørning')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8400','Ebeltoft')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8410','Rønde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8500','Grenaa')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8592','Anholt')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8600','Silkeborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8660','Skanderborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8700','Horsens')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8722','Hedensted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8765','Klovborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8781','Stenderup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8783','Hornsyld')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8800','Viborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8831','Løgstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8860','Ulstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8950','Ørsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('8990','Fårup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9000','Aalborg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9240','Nibe')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9260','Gistrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9270','Klarup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9280','Storvorde')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9293','Kongerslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9300','Sæby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9320','Hjallerup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9340','Asaa')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9352','Dybvad')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9362','Gandrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9370','Hals')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9380','Vestbjerg')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9381','Sulsted')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9382','Tylstrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9460','Brovst')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9480','Løkken')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9492','Blokhus')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9493','Saltum')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9500','Hobro')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9520','Skørping')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9530','Støvring')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9541','Suldrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9550','Mariager')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9560','Hadsund')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9600','Aars')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9610','Nørager')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9620','Aalestrup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9640','Farsø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9700','Brønderslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9800','Hjørring')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9830','Tårs')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9850','Hirtshals')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9870','Sindal')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9881','Bindslev')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9900','Frederikshavn')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9940','Læsø')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9970','Strandby')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9981','Jerup')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9982','Ålbæk')
INSERT INTO [dbo].[post_nr_by] ([post_nr], [by_navn]) VALUES ('9990','Skagen')
